### ISSUE TITLE
Proposal for a contribution

### ISSUE THREAD

**Issue by claustres** [danwild/leaflet-velocity#6]
Dear Dan, for a project using weather forecast data I’ve been involved into I discovered your work, mainly https://github.com/danwild/wind-js-server and https://github.com/danwild/leaflet-velocity. I started modifying your code https://github.com/weacast/wind-server but then I decided starting an effort to create a more generic Open Source platform on this topic : https://github.com/weacast. 

It is a work in progress but I start having a running base, you have some information here https://weacast.gitbooks.io/weacast-docs/. Because you have done a similar work before I wonder if you were interested in collaborating to create a GFS plugin for Weacast ? I think we could also work on improving leaflet-velocity or creating npm module to share some code parts.

Sorry using the issue tracker for this but didn't know how to contact you otherwise (your GitHub e-mail does not seem to work), let me know any other prefered way to contact you.

Thanks in advance for your return,

**Comment by danwild** [comment]
Hi @claustres. 
Thanks for your interest in the project, glad you find it useful!

Unfortunately; I don't even have time available to work on _this_ project at the moment, I am mostly just in maintenance mode for now (with some possible movement into 3D visualisation being considered for the future).

I will watch the Weacast project with interest, however I am unable to commit to any meaningful development work at this stage due to an already hectic work schedule.. (however please feel to contact me if you have any specific questions).

I have noticed your PR's and hope to merge them soon - thank you for your contributions!

Cheers,
Dan

**Comment by claustres** [comment]
3D is also one of my expertise and I will probably add something in Weacast based on Cesium, so we have to keep in touch.

About the PRs I started a fork anyway https://github.com/weacast/leaflet-velocity to be able to publish before you integrated it but I will do my best to keep projects in sync.

Thanks for your reply
